server:
  port: 8083


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: berilguner


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true